- fix: error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax - fix: uchardet library doesn't have it's export header file in uchardet/uchardet.h but in include/uchardet.h: use the #include sans path prefix